### ISSUE TITLE
Breaks when used in a subdirectory

### ISSUE THREAD

**Issue by bitjson** [reg-viz/reg-cli#124]
Thanks for the excellent tool!

The CLI seems to expect activity to happen in the current working directory. This npm script causes several errors:

```json
{
    "visual:approve": "reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json"
}
```

But this one works perfectly:
```json
{
    "visual:approve": "cd test && reg-cli latest approved diffs --report report.html --json report.json"
}
```

A sampling of the errors:
`Error: ENOENT: no such file or directory, unlink './approved/[IMG]'`
`Error: ENOENT: no such file or directory, open './latest/[IMG]`

It's also possible I'm just misunderstanding the usage.

**Comment by bokuweb** [comment]
@bitjson Hi, thanks for your report :)

Hmm, I can not reproduce that errors.
I created minimum sample repository trying to reproduce it. ( But `reg-cli` run correctly in my env...)

https://github.com/bokuweb/reg-example

Could you please try run `npm run visual:approve` or `yarn visual:approve` with above repository, if you get a chance.

**Comment by bitjson** [comment]
Wow, thanks for the quick response @bokuweb!

```
$ git clone git@github.com:bokuweb/reg-example.git
[...]
$ cd reg-example/
$ npm run visual:approve

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json

✘ change  test/latest/sample.png


✘ 1 file(s) changed.

Inspect your code changes, re-run with `-U` to update them. 
```

Trying to update:

```
$ npm run visual:approve -- -U

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json "-U"

✘ change  test/latest/sample.png
Error: ENOENT: no such file or directory, unlink './approved/sample.png'

```

**Comment by bitjson** [comment]
Also – I'm not sure if I'm misunderstanding usage. I should be able to delete the file in `approved`, and when I run with `--update`, the file from `latest` should be copied in, correct?

```
$ rm test/approved/sample.png 
$ npm run visual:approve -- -U

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json "-U"

✚ append  test/latest/sample.png
Error: ENOENT: no such file or directory, unlink './approved/sample.png'

$ cd test && reg-cli latest approved diffs --report report.html --json report.json -U
✚ append  latest/sample.png
Error: ENOENT: no such file or directory, unlink './approved/sample.png'

```

**Comment by bokuweb** [comment]
@bitjson I see. 

>  when I run with --update, the file from latest should be copied in, correct?

You're right. If you set `-U` actual images copy to expected images. They are used as expected images next regression test. It is inspired by `jest` snapshot test.

> ✚ append  test/latest/sample.png
Error: ENOENT: no such file or directory, unlink './approved/sample.png'

I think, it is `reg-cli`'s bug. I'll investigate it.

**Comment by bokuweb** [comment]
@bitjson Could you please try `v0.11.1` ?

**Comment by bitjson** [comment]
Hey @bokuweb – with `v0.11.1`:

```
$ git reset --hard
[...]
$ npm install reg-cli
npm WARN reg-example@1.0.0 No description

+ reg-cli@0.11.1

$ npm run visual:approve

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json

✘ change  test/latest/sample.png


✘ 1 file(s) changed.

Inspect your code changes, re-run with `-U` to update them. 
```

Trying to update:

```
$ npm run visual:approve -- -U

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json "-U"

✘ change  test/latest/sample.png
Error: ENOENT: no such file or directory, scandir './approved'
```

And after removing:
```
$ rm test/approved/sample.png 
$ npm run visual:approve -- -U

> reg-example@1.0.0 visual:approve /Users/jason/Workspace/test/reg-example
> reg-cli test/latest test/approved test/diffs --report test/report.html --json test/report.json "-U"

✚ append  test/latest/sample.png
Error: ENOENT: no such file or directory, scandir './approved'
```

So this appears to still be an issue.

**Comment by bokuweb** [comment]
Oops, sorry... fixed by https://github.com/reg-viz/reg-cli/pull/126.

**Comment by bitjson** [comment]
Fantastic, thanks! Seems to be working as expected now. 👍
