### ISSUE TITLE
Proposal: image "variants" for better cross-platform testing

### ISSUE THREAD

**Issue by bitjson** [reg-viz/reg-cli#135]
I'm trying to set up `reg-cli` for [Copay](https://github.com/bitpay/copay), an Ionic app we build for iOS, Android, and desktop (macOS, Windows, and Linux).

I'm having some trouble avoiding false positives from very slight rendering differences between Chrome screenshots taken on macOS and those taken on Linux. 

Almost everything is the same, but some font and shadow antialiasing seems to be different, and it's causing false positives. There are also some platform differences causing problems (scroll bars, file upload buttons).

Here's the comparison report from our CI: https://1043-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html

There are a few real issues mixed in with the false positives here, but I wanted to open this issue since it may be possible to solve a lot of these with improvements to reg-cli.

# 1: Antialiasing issues

**For this case: [![screen shot 2018-03-27 at 10 34 43 am](https://user-images.githubusercontent.com/904007/37974269-7cdfa48e-31aa-11e8-977b-0e0bb08827b2.png)](https://1043-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html#%2Fcopay%2Fimport-wallet-with-encryption-input-confirm_Nexus5X.png)**

I really don't know the best way to handle this issue. We're currently using the [reg-cli settings: ` --enableAntialias --thresholdRate 0.005`](https://github.com/bitjson/copay/blob/04665fd6ab41d1d26fe9e8a40168d53c0576ba98/app-template/package-template.json#L64).

Any recommendations for improving this? I'm afraid if I raise the `thresholdRate` more, we'll start missing real issues.

It would also be helpful to understand what the diff is showing. What is yellow vs. red in the diff?

# 2: Scrollbars

I'm also trying to figure out the best way to handle platform rendering differences like scrollbars:

[![screen shot 2018-03-27 at 10 38 21 am](https://user-images.githubusercontent.com/904007/37974518-1f4edad2-31ab-11e8-8a37-04fbee706535.png)](https://1043-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html#%2Fcopay%2Fhome_1024x720.png)

Our options here:
A. **Avoid any cross platform differences** – e.g. render our own custom scrollbar on both platforms
    - we would prefer to use the native scrollbar, so this is not really an option
B. **Hide conflicting elements for e2e tests** –  we could inject CSS like `* { ::-webkit-scrollbar {   
 display: none; }` just to take screenshots
   - this is also not ideal, since we'd like screenshots to match the real application as best as possible
C. **Give `reg-cli` both a macOS and Linux version, so the test passes if either matches.**

What are your thoughts on option `C`? If `reg-cli` could accept one or more `variant`s for each image, I think this might also offer a better solution for our `Antialiasing issues` above. 

# Proposal

For images with lots of antialiasing problems, we can provide a version for both macOS and Linux.

Maybe a new command line option like:

`--variantRegex` the regex used to identify variants for each image. If omitted, [`(.*)-variant-[-0-9].`](https://regexr.com/3mv0o)

With the default setting, if my previous image list looked like:
```
test-image.png
test-image-variant-1.png
another-test.png
another-test-variant-1.png
another-test-variant-2.png
```

`test-image-variant-1.png` would match the default `variantRegex`, with a capturing group value of `test-image`. And both `another-test-variant-1.png` and `another-test-variant-2.png` would both have a captured value of `another-test`.

When testing a new `test-image.png`, `reg-cli` would first test against the existing `test-image.png`. 

If it passes we're done. If it fails, test against each variant for `test-image` (removing the `.png` to match the capturing groups). 

If any variant passes, pass the test. If all variants fail, we use the closest variant for the diff. This allows us to specifically "pass" certain cross-platform differences, without missing real, unintentional changes.

Any thoughts on this idea?

**Comment by bokuweb** [comment]
Thanks for your proposal. I will review and answer later.

**Comment by bokuweb** [comment]
@bitjson 

> 1: Antialiasing issues

That is a difficult problem. I have a similar problem and I am avoiding it in my project as follows for now.

### Using `-S, --thresholdPixel`

In my project, I use `reg-cli settings: --thresholdPixel 20`.This is because if the image is large, the threshold will be too large. (It may miss the real issue.)

### To add a delay before taking a screenshot

I add a subtle delay before taking a screenshot like below.

``` js
requestIdleCallback(() => screenshot())
```

If you still miss it, I use `setTimeout`

``` js
setTimeout(() => screenshot(), 100)
```
> It would also be helpful to understand what the diff is showing. What is yellow vs. red in the diff?

`reg-cli` use `mapbox/pixelmatch` to create diff image. I think,  yellow is `anti-aliased pixels detection ` and red is `perceptual color difference metrics`

These are difficult problems and are seeking a better way.

**Comment by bokuweb** [comment]
> 2: Scrollbars
> What are your thoughts on option C? If reg-cli could accept one or more variants for each image, I think this might also offer a better solution for our Antialiasing issues above.

Agree. The application should not be modified as much as possible for testing

**Comment by bokuweb** [comment]
> Proposal

It looks cool :) However, I do not yet understand the image of actual operation.
For example,  are you planning to prepare the following images in your project? (And the following images subtly different?)

```
/copay/home_iPhone8.png
/copay/home_iPhone8-variant-1.png
/copay/home_iPhone8-variant-2.png
/copay/home_iPhone8-variant-3.png
```

**Comment by bitjson** [comment]
@bokuweb yes, in the Copay example, we would run the tests locally, and it would generate the screenshots. (E.g. run e2e tests in two browser instances, one simulating `iPhoneX`, and the other `desktop`):

```
latest/copay/onboarding_iPhoneX.png
latest/copay/onboarding_desktop.png
latest/copay/home_iPhoneX.png
latest/copay/home_desktop.png
```

Imagine my changes add the 4 images above. I review them, then I re-run our reg-cli script with `-U`.

Now if I run the full test suite again, it passes.

So we've added the 4 images to our `expected` folder (we call it `approved`):
```
approved/copay/onboarding_iPhoneX.png
approved/copay/onboarding_desktop.png
approved/copay/home_iPhoneX.png
approved/copay/home_desktop.png
```

The 2 `onboarding` screenshots don't have scroll bars, so they should be exactly the same on all platforms. Likewise, our app replaces the scroll bar with a custom component on `home_iPhoneX.png`, so it renders the same on all development and CI machines. 

However, the `home_desktop.png` screenshot **uses native scroll bars**, and will render differently on our Linux CI machine than it did on my macOS development machine. (And this is good, we want to be able to easily test both.)

Since I'm on macOS, `approved/copay/home_desktop.png` has the macOS scroll bar.

I commit my changes, and open a PR on GitHub. CircleCI automatically tests my PR, but the build fails. I look at reg-cli's diff ([example](https://1094-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html)), and find that the difference is just the scroll bar:

<img width="1537" alt="screen shot 2018-03-28 at 10 46 15 am" src="https://user-images.githubusercontent.com/904007/38036733-5bdaa984-3275-11e8-8fee-9b074d2e8cae.png">
 
Everything else looks as expected. 

## Adding a variant

Following the proposal above, I could set `--variantRegex` to `(.*)-variant-[-a-zA-Z].`. Then I copy the screenshot generated by the Linux machine to:

```
approved/copay/home_desktop-variant-linux.png
```

And commit it. When I run the tests again locally, `reg-cli` does exactly what it did before, ignoring the variant, because all tests pass (on macOS).

When I push the commit to GitHub, CircleCI starts a new build with my change.

When `reg-cli` runs again, it will find that there is a failing difference between `approved/copay/home_desktop.png`, the original screenshot with a macOS scroll bar, and `latest/copay/home_desktop.png`, the screenshot generated on CircleCI using Linux, which shows the linux scroll bar.

When `reg-cli` sees this failure, it should look for `variantRegex` matches in all the images now in `approved`:
```
approved/copay/onboarding_iPhoneX.png
approved/copay/onboarding_desktop.png
approved/copay/home_iPhoneX.png
approved/copay/home_desktop.png
approved/copay/home_desktop-variant-linux.png
```

The only match is `home_desktop-variant-linux.png`, which has a capture group of `home_desktop`. 

Since the test for `home_desktop` is failing:

`latest/copay/home_desktop.png` == `approved/copay/home_desktop.png` // failing

`reg-cli` tries again with the variant:

`latest/copay/home_desktop.png` == `approved/copay/home_desktop-variant-linux.png` // passes

Since the test passes against a variant, it is marked as passing.

## Failing tests with variants

If `reg-cli` found that none of the variants were close enough, it would still fail the test. 

In the report, `reg-cli` should display the diff image of the **closest match**. In the case above, imagine I completely changed the contents of `home_desktop`.

On CircleCI, the image will have very little in common with `approved/copay/home_desktop.png`, both the contents and the scroll bar are different. However, the scroll bars will match with `approved/copay/home_desktop-variant-linux.png`. 

So the diff image for:

`latest/copay/home_desktop.png` == `approved/copay/home_desktop-variant-linux.png`

will be shown.

**Comment by bokuweb** [comment]
@bitjson I see. It looks good:) But If `--variantRegex` not set, I think it would be better to disable the feature of the variant.

**Comment by bitjson** [comment]
Update on this: after a lot of messy work trying to make our e2e system work better cross platform, I ultimately ended up switching the project to running the tests in a more controllable Docker container. You can [read more about our process here](https://github.com/bitpay/copay/tree/0914593c05e2c74357142594cbb6ad81f467dc49/test/visual).

So now we're building everything on Linux, which solves most of our issues above. I don't know if I would still recommend building a `varientRegex` option, I think it may be best to recommend projects take their screenshots in Docker or something similar.

And if you're interested, here's an example build:

BitPay [build#1161](https://circleci.com/gh/bitpay/copay/1161) – [`reg-cli` report](https://1161-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html)
Copay [build#1162](https://circleci.com/gh/bitpay/copay/1162) – [`reg-cli` report](https://1162-18141084-gh.circle-artifacts.com/0/home/circleci/copay/test/visual/report.html)

I'm going to close this issue for now, but feel free to reopen it if you still want to pursue the idea.
