### ISSUE TITLE
Error when using the --update flag in project with subdirectories

### ISSUE THREAD

**Issue by bitjson** [reg-viz/reg-cli#136]
This is a similar issue to https://github.com/reg-viz/reg-cli/issues/124. In a project like:

https://github.com/bokuweb/reg-example

If instead of `test/approved/sample.png`, I have subdirectories inside of `approved`, like:

```
test/approved/app1/sample.png
test/approved/app2/sample.png
```

When I run the update operation, I'll get the error:

```
Error: EPERM: operation not permitted, unlink 'test/visual/approved/app1'
```

It appears that `cleanupExpectedDir` expects a flat folder. Everything else seems to work fine with subdirectories.

**Comment by bitjson** [comment]
I might be best to use [del](https://www.npmjs.com/package/del) here.

It also prevents accidental deletions (by bugs) outside of the current working directory.

**Comment by bokuweb** [comment]
@bitjson Thanks for your report. I'll do an investigation and try `del` later.
