### ISSUE TITLE
Add some image comparison tools

### ISSUE THREAD

**Issue by priomsrb** [reg-viz/reg-cli#190]
Hi,

I'm using this tool standalone in my visual regression set up. The report it generates is quite nice.

I was looking to improve the report by adding more image comparison tools. For an example see github's image diff in commits: https://github.com/cameronmcefee/Image-Diff-View-Modes/commit/8e95f70c9c47168305970e91021072673d7cdad8?short_path=eda75e0#diff-eda75e03d7033f3550356ddb8363ed56

Would you be interested in having something like that? I could try implementing something like that myself and put up a pull request. I was just wondering if you already have plans for doing something like that.

**Comment by bokuweb** [comment]
@priomsrb Hi :) Thanks for your suggestion 👍 

> I could try implementing something like that myself and put up a pull request.

Yeah. That's cool :) I am looking forward to it. Thanks.

**Comment by priomsrb** [comment]
Hi @bokuweb 

I've put up a PR which adds some different comparison modes. Let me know if it looks good to you.

**Comment by bokuweb** [comment]
@priomsrb Thanks for your great PR 👍 It looks so cool :) I'll check it. thanks.
