### ISSUE TITLE
pass custom fail message

### ISSUE THREAD

**Issue by sag1v** [reg-viz/reg-cli#425]
Currently when tests are failing for any reason we get this message in terminal:

> Inspect your code changes, re-run with `-U` to update them

The issue with this message is that in some cases running the reg-cli command is used with an npm/yarn script.  
For example - `yarn test:visual`.

So developers that are using the repo think they need to run `yarn test:visual -U` but this will just run the test again, what they really need to run is another dedicated script for updating e.g: `yarn test:visual:update`.

It would be great to pass reg-cli a fail message (we can also pass success message if you think its needed) that will be used in case of a fail. The default message can be the message we have today.

**Comment by sag1v** [comment]
@bokuweb WDYT? If this is something you guys think should be added i don't mind to create a PR.

**Comment by bokuweb** [comment]
@sag1v Sorry for late. looks good. could you please create PR?

**Comment by sag1v** [comment]
@bokuweb sure #439
