### ISSUE TITLE
mkdirp not listed in package.json

### ISSUE THREAD

**Issue by sr258** [reg-viz/reg-cli#480]
There is an [import of `mkdirp` in report.js](https://github.com/reg-viz/reg-cli/blob/c6f6aa5392f9eb00c14b6a3cedea1378c4048e49/src/report.js#L7), but `mkdirp` is not included in package.json. 

The result is that `reg-cli` doesn't work for my application, as I use `mkdirp` in a newer major version (v3) there. As the dependency is missing in `reg-cli`'s depedency list, NPM doesn't install a local version for `reg-cli` but uses the one installed for my application (v3). v3 and v2 are not compatible.

The solution would add `mkdirp` to the dependency list.

**Comment by bokuweb** [comment]
@sr258 Thanks please try 0.18.0
