### ISSUE TITLE
HTML report generation fails because `style.css` wasn’t found

### ISSUE THREAD

**Issue by geigerzaehler** [reg-viz/reg-cli#494]
When I try to generate an HTML report I get an error that `style.css` wan’t found. This worked on 0.18.1 but broke on 0.18.2

## Reproduction

1. Run `reg-cli a b c -R r`

Then I see the error
> Error: ENOENT: no such file or directory, open '...node_modules/.pnpm/reg-cli@0.18.2/node_modules/reg-cli/report/ui/dist/style.css'

**Comment by bokuweb** [comment]
@geigerzaehler Sorry Please use 0.18.5
