### ISSUE TITLE
Report cannot be opened through "file" protocol since ReportUI 3.0 

### ISSUE THREAD

**Issue by ajkl2533** [reg-viz/reg-cli#506]
## Describe the bug

Up until releasing new version of ReportUI I could simply open generated report via `file` protocol (e.g. `file:///path/to/report/report.html`). Yesterday I upgraded from 0.18.1 to latest version 0.18.6 and when I tried to open the report in my browser I got only white page and an error message in console `Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///.../.storybook/image-snapshots/worker.js' cannot be accessed from origin 'null'.`

When I use http server to serve the report everything goes fine, but we are storing the report as an artifact in our CI and I cannot run server there to see the results.

## Reproduced step

1. Generate report with reg-cli@0.18.6
2. Right click on `report.html` and Copy path
3. Paste path into URL bar in browser

## Expected behavior

Report can be opened via `file` protocol as before

## Actual behavior

Report can be opened only if it's served with http server.

## Screenshots

<img width="849" alt="Screenshot 2024-06-25 at 16 26 48" src="https://github.com/reg-viz/reg-cli/assets/18654425/6c964583-86fb-4a7b-9d70-00f7ed8e840b">

**Comment by kumarpatel** [comment]
Seeing the exact the same behaviour.
And exact same implication as described by @ajkl2533 around storing it as an artifact in CI.

I'm using this indirectly via reg-suit@14.4

**Comment by bokuweb** [comment]
@ajkl2533 @kumarpatel Could you please try latest version?

**Comment by kumarpatel** [comment]
Confirmed. Working now. 🟢

**Comment by dmitry-platogo** [comment]
It is still not working when using `reg-cli@0.18.6`
