### ISSUE TITLE
The version published on npm is marked as experimental

### ISSUE THREAD

**Issue by umkw** [reg-viz/reg-cli#511]
## Details
The npm package [reg-cli](https://www.npmjs.com/package/reg-cli) has `0.0.0-experimental-13` as the latest version, and it seems that the README is missing.

After updating the package and running `reg-cli`, the following error occurred:
`***/node_modules/.bin/reg-cli: line 1: import: command not found`.

**Comment by bokuweb** [comment]
@umkw Sorry, 0.18.8 published as latest version
